apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-gitops-runtime
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/testcodefresh/pre-prod-shared-config-e2e-rl-flow.git
    targetRevision: HEAD
    path: resources/test-date/chart
    helm:
      releaseName: cf-gitops-runtime
  destination:
    namespace: test-date
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
