apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-test
  labels:
    codefresh.io/entity: integration-config
    codefresh.io/integration-type: issue.jira
data:
  host_url: https://codefresh-io.atlassian.net
  email: bohdan.pisarenko@codefresh.io
